### ISSUE TITLE
Slack Invites

### ISSUE THREAD

**Issue by bhalothia** [TheRemoteLab/theremotelab.github.io#22]
We should be able to allow people to signup for our DevOps channel (https://letsdevops.slack.com)

**Comment by bhalothia** [comment]
@ramitsurana Can you check this again? https://blog.stamplay.com/launch-your-community-with-a-fully-automated-slack-signup-page/

**Comment by ramitsurana** [comment]
Check out https://letsdevops.stamplayapp.com/

**Comment by ramitsurana** [comment]
Fixed using http://letsdevops.herokuapp.com
